=== jemmaliMM/attractouch/output/content/levels/level.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by Remi Gillig (speps) -->
<!--Positions and sizes are in pixels and in reference to a 1280x1024 resolution-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:level="http://speps.fr/attractouch/level" targetNamespace="http://speps.fr/attractouch/level">
	<xs:complexType name="vectorType">
		<xs:attribute name="x" type="xs:int" use="required"/>
		<xs:attribute name="y" type="xs:int" use="required"/>
	</xs:complexType>
	<xs:complexType name="velocityType">
		<xs:sequence>
			<xs:element name="position" type="level:vectorType"/>
			<xs:element name="direction" type="xs:float" default="0"/>
			<xs:element name="strength" type="xs:float" default="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="rectangleType">
		<xs:attribute name="x" type="xs:int" use="required"/>
		<xs:attribute name="y" type="xs:int" use="required"/>
		<xs:attribute name="width" type="xs:unsignedInt" use="required"/>
		<xs:attribute name="height" type="xs:unsignedInt" use="required"/>
	</xs:complexType>
	<xs:complexType name="launcherType">
		<xs:sequence>
			<xs:element name="initialParticles" type="xs:unsignedShort" default="10"/>
			<xs:element name="position" type="level:vectorType" nillable="false"/>
			<xs:element name="speed" type="xs:float" default="1"/>
			<xs:element name="direction" type="xs:float" default="0"/>
			<xs:element name="radius" type="xs:unsignedInt" default="60"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="launchersType">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="launcher" type="level:launcherType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="receiverType">
		<xs:sequence>
			<xs:element name="position" type="level:vectorType"/>
			<xs:element name="radius" type="xs:unsignedInt" default="60"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="wallsType">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="wall" type="level:rectangleType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="flowType">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="velocity" type="level:velocityType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="levelType">
		<xs:sequence>
			<xs:element name="mainLauncher" type="level:launcherType" nillable="false"/>
			<xs:element name="optionalLaunchers" type="level:launchersType" nillable="false"/>
			<xs:element name="receiver" type="level:receiverType" nillable="false"/>
			<xs:element name="walls" type="level:wallsType" nillable="false"/>
			<xs:element name="flow" type="level:flowType" nillable="false"/>
		</xs:sequence>
		<xs:attribute name="rate" type="xs:float" default="1"/>
		<xs:attribute name="nextLevel" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:element name="level" type="level:levelType"/>
</xs:schema>

=== jemmaliMM/attractouch/output/content/levels/level3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by Remi Gillig (speps) -->
<at:level xmlns:at="http://speps.fr/attractouch/level" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://speps.fr/attractouch/level level.xsd" rate="1.5" nextLevel="level4">
	<mainLauncher>
		<initialParticles>15</initialParticles>
		<position x="1150" y="100"/>
		<speed>1</speed>
		<direction>180</direction>
		<radius>60</radius>
	</mainLauncher>
	<optionalLaunchers/>
	<receiver>
		<position x="100" y="880"/>
		<radius>100</radius>
	</receiver>
	<walls>
		<!-- tour de mur -->
		<wall height="1024" width="15" x="1265" y="0"/>
		<wall height="15" width="1050" x="0" y="0"/>
		<wall height="15" width="900" x="500" y="1000"/>
		
		<!-- ld -->
		<!-- forme 1 -->
		<!-- pointe haut -->
		<wall height="350" width="50" x="500" y="200"/>
		<wall height="50" width="210" x="300" y="300"/>
		<!-- centre -->
		<wall height="50" width="660" x="500" y="500"/>
		<!-- pointe bas -->
		<wall height="50" width="410" x="870" y="700"/>
		
		<!-- tige en bas a droite -->
		<wall height="300" width="50" x="650" y="500"/>
		
		<!-- tige en bas a gauche -->
		<!--<wall height="250" width="50" x="400" y="750"/>-->
		
		<!-- tiges noires haut droite -->
		<wall height="300" width="15" x="800" y="0"/>
		<!--<wall height="100" width="15" x="800" y="400"/>-->
		<!-- tiges noires haut gauche -->
		<wall height="400" width="15" x="100" y="0"/>
		<wall height="15" width="300" x="00" y="600"/>
		
	</walls>
	<flow>
		<velocity>
			<position x="100" y="100"/>
			<direction>-45</direction>
			<strength>1</strength>
		</velocity>
	</flow>
</at:level>
